name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # Deploy on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build the Project
      run: npm run build

    - name: Zip Deployment Package
      run: |
        cd dist
        zip -r ../lambda.zip ./

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@v0.0.6
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        function_name: lamdafunction_test
        zip_file: ./lambda.zip
